### ISSUE TITLE
get userId by @userName

### ISSUE THREAD

**Issue by chaevnicher** [nadam/userinfobot#1]
how I can get userId by @userName

**Comment by milad1400** [comment]
properties

**Comment by robertnicjoo** [comment]
same issue, it always shows mine when i try to get my bot id

**Comment by matiniamirhossein** [comment]
You cannot do that. That's not possible with the current bot api.

Btw it's possible using a telegram api (with phone number not bot) but it has lot's of limitations. Don`t waste your time.
