### ISSUE TITLE
Telegram ID is now int64, and the bot seems not working on new int64 UID users.

### ISSUE THREAD

**Issue by playard** [nadam/userinfobot#9]
Originally user ID was int32 up to 2147483647 and has been run out weeks or months ago. 

From what I've heard from another bot operator, simply update/re-deploy the TDLib might do the trick. He was using an "air quote" or a strike line there, so I'm not sure if it's ture.

**Comment by playard** [comment]
> From what I've heard from another bot operator, simply update/re-deploy the TDLib might do the trick. He was using an "air quote" or a strike line there, so I'm not sure if it's ture.

Seems working now! Happy New Year.

**Comment by nadam** [comment]
Thanks for reporting. I've updated the code in the repo as well now.
